/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bebo_
 */
public class frmSeidel extends javax.swing.JFrame {
    final static int MAXN=10;
    static double a[][]=new double[MAXN][MAXN];
    static double error;//escribir el error
    static double x1[]=new double[MAXN];// Se usa para guardar el valor para la iteración
    static double errr;
    static double err_anterior=0;
    static int numIncog;
     
        
    /**
     * Creates new form frmSeidel
     */
    public frmSeidel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtincog = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsistema = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbliteracion = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbliteracion2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaSolu = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de incognitas");

        txtsistema.setColumns(20);
        txtsistema.setRows(5);
        jScrollPane1.setViewportView(txtsistema);

        jLabel2.setText("Error");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtincog)
                    .addComponent(txtError, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtincog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbliteracion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbliteracion.setEnabled(false);
        jScrollPane3.setViewportView(tbliteracion);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 155));

        tbliteracion2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbliteracion2.setEnabled(false);
        tbliteracion2.setRowSelectionAllowed(false);
        jScrollPane5.setViewportView(tbliteracion2);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 590, 155));

        txtaSolu.setEditable(false);
        txtaSolu.setColumns(20);
        txtaSolu.setRows(5);
        jScrollPane4.setViewportView(txtaSolu);

        jLabel3.setText("soluciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String texto="";
        DefaultTableModel modelo= (DefaultTableModel) tbliteracion.getModel();
         DefaultTableModel modelo2= (DefaultTableModel) tbliteracion2.getModel();
        numIncog=Integer.parseInt(txtincog.getText());
        error=Double.parseDouble(txtError.getText());
        Object[] fila = new Object[numIncog*3];
        String[] pa = txtsistema.getText().split("\n");
        for(int i=0;i<numIncog;i++){
            String p1=pa[i];
            //System.out.println(pa[i]);
            
            String [] pa2 = pa[i].split(" ");
            for(int j=0; j<numIncog+1;j++){
                String p2=pa2[j];
                a[i][j] = Double.parseDouble(String.valueOf(pa2[j]));
            }
         }
        
               modelo.addColumn("No.");
          
        for(int i=0;(i<numIncog);i++){
               modelo.addColumn("x"+(i+1));
          }
           for(int i=0;(i<numIncog);i++){
            modelo2.addColumn("Xn"+(i+1));
           }
           for(int i=0;(i<numIncog);i++){
            modelo2.addColumn("Error"+(i+1));
           }
           modelo.setRowCount(0);
           modelo2.setRowCount(0);
        for(int i=0;i<numIncog;i++){
            //x1[i]=sc.nextDouble();
            x1[i]=0;
            fila[0]=1;
            fila[(i+1)]=x1[i];
            
        }
        
         modelo.addRow(fila);
         tbliteracion.setModel(modelo);
        
        for(int i=0;i<numIncog;i++){// Escribe el sistema de ecuaciones como un sistema equivalente de ecuaciones
            for(int j=0;j<=numIncog;j++){
                if(j<numIncog&&j!=i){
                    a[i][j]=-(a[i][j]/a[i][i]);
                }else if(j==numIncog){
                    a[i][j]=(a[i][j]/a[i][i]);
                }
            }
            a[i][i]=0;
        }
        
        int i=0;
        do{
           diedai();
            i++;
           
        }while(error<errr && error<errr);
         double inicial[] =new double[i];
        for(i=1;i<inicial.length+1;i++){
            modelo.setValueAt(i+1, i,0);
        }
        for(i=0;i<numIncog;i++)
            texto+="x"+(i+1)+"= "+redondear(x1[i])+"\n";
        
        txtaSolu.setText(texto);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeidel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private static javax.swing.JTable tbliteracion;
    private static javax.swing.JTable tbliteracion2;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextArea txtaSolu;
    private javax.swing.JTextField txtincog;
    private javax.swing.JTextArea txtsistema;
    // End of variables declaration//GEN-END:variables
static void diedai(){
          DefaultTableModel modelo= (DefaultTableModel) tbliteracion.getModel();
          DefaultTableModel modelo2= (DefaultTableModel) tbliteracion2.getModel();
           
           Object[] fila = new Object[numIncog*3];
           Object[] fila2 = new Object[numIncog*3];
        for(int i=0;(i<numIncog);i++){
             double temp=0;
            for(int j=0;j<numIncog;j++){
                temp+=x1[j]*a[i][j];
            }
            
            temp+=a[i][numIncog];//valor anterior de las x
            fila[(i+1)]=redondear(temp);
            
            errr=(Math.abs((x1[i]-temp)/x1[i]))*100;
            
            x1[i]=temp;
            fila2[i]=redondear(x1[i]);
               
            //filas del error    
            if(Double.isInfinite(errr))
                fila2[i+numIncog]=100;
            else
            fila2[i+numIncog]=redondear(errr);
            
        }
        
        
        modelo.addRow(fila);
        modelo2.addRow(fila2);
        tbliteracion.setModel(modelo);
        tbliteracion2.setModel(modelo2);
        
    }
public static double redondear(double valor){
        BigDecimal bd = new BigDecimal(valor).setScale(6,RoundingMode.HALF_UP);
        return bd.doubleValue();
    }
}
